version: '3.3'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mysqldb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - app-mysqldb:/var/lib/mysql

volumes:
  app-mysqldb:
