version: '3.3'

volumes:
  mysql_data:
  mongodb_data:
  rabbitmq_data:

networks:
  app_network:
    driver: bridge

services:

  admin:
    container_name: admin
    build: ./packages/admin
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - mysqldb
    links:
      - rabbitmq
      - mysqldb
    networks:
      - app_network

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mysqldb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '5000:80'
    environment:
      PMA_HOST: mysqldb
    depends_on:
      - mysqldb
    networks:
      - app_network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'user'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
      MONGO_INITDB_DATABASE: 'mongodb'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  mongoex:
    container_name: mongoex
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
        - ME_CONFIG_MONGODB_AUTH_DATABASE=mongodb
        - ME_CONFIG_MONGODB_AUTH_USERNAME=user
        - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
        - ME_CONFIG_BASICAUTH_USERNAME=user
        - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
        - mongodb
    ports:
      - "8888:8081"
    networks:
      - app_network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/etc/rabbitmq/
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_data:/var/log/rabbitmq/
    networks:
      - app_network
