version: '3.3'

volumes:
  app-data:

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mysqldb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - app-data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'user'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
      MONGO_INITDB_DATABASE: 'mongodb'
    ports:
      - 27017:27017
    volumes:
      - app-data:/data/db

  rabbitmq:
    image: rabbitmq:3.8
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - app-data:/var/lib/rabbitmq/
        - app-data:/var/log/rabbitmq

